refactor: unit test gate step

diff --git a/.github/workflows/static-checks.yaml b/.github/workflows/static-checks.yaml
--- a/.github/workflows/static-checks.yaml
+++ b/.github/workflows/static-checks.yaml
@@ -71,6 +71,20 @@ jobs:
           name: coverage
           path: coverage/lcov.info
           retention-days: 1
+  unit-test-gate:
+    name: Unit tests result
+    runs-on: ubuntu-latest
+    needs: unit-test
+    if: always()
+    steps:
+      - run: |
+          if [[ "${{ needs.unit-test.result }}" == "success" || "${{ needs.unit-test.result }}" == "skipped" ]]; then
+            echo "Tests passed or were correctly skipped"
+            exit 0
+          else
+            echo "Tests failed"
+            exit 1
+          fi
   codecov:
     name: Codecov
     runs-on: ubuntu-latest
